name: Build and publish

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/*.md'
      - '**/*.yml'
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    name: Build and publish
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: package.json

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build
        run: bun run build

      - name: Zip artifact
        run: bun run package

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: v${{ github.run_number }}
          files: ./artifacts/release.zip
          generate_release_notes: true
